/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DaggerDemo;

import org.junit.Test;
import static org.junit.Assert.*;

public class CommandLineAtmTest {
    @Test public void testAppHasAGreeting() {
        CommandLineAtm classUnderTest = new CommandLineAtm();
//        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
