/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DaggerDemo;

import DaggerDemo.base.Command;
import DaggerDemo.helloworld.HelloWorldModule;
import DaggerDemo.login.LoginCommandModule;
import DaggerDemo.output.SystemOutModule;
import DaggerDemo.user.AmountsModule;
import DaggerDemo.user.UserCommandsRouter;
import dagger.Component;

import javax.inject.Singleton;
import java.util.Scanner;

public class CommandLineAtm {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
//        CommandRouter commandRouter = new CommandRouter();
//        CommandRouterFactory commandRouterFactory = DaggerCommandRouterFactory.create();
//        CommandRouter commandRouter = commandRouterFactory.router();
        CommandProcessorFactory commandProcessorFactory = DaggerCommandLineAtm_CommandProcessorFactory.create();
        CommandProcessor commandProcessor = commandProcessorFactory.processor();

        while (scanner.hasNextLine()) {
            Command.Status status = commandProcessor.process(scanner.nextLine());
            if (status == Command.Status.INVALID) break;
        }
        scanner.close();
    }

    @Singleton
    @Component(modules = {
            HelloWorldModule.class,
            SystemOutModule.class,
            AmountsModule.class,
            UserCommandsRouter.InstallationModule.class,
            LoginCommandModule.class
    })
    interface CommandProcessorFactory {
        CommandProcessor processor();
    }
}
